config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
get 'posts/index'
resources:posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true, length: { maximum: 50 }, on:[:create, :update]
    validates :begin_day, presence: true, on: :create
    validates :finish_day, presence: true, on: :create
    validate :date_before_start, on: :create
  def date_before_start
    if begin_day.present? && begin_day < Date.today
    errors.add(:begin_day, "は今日以降のものを選択してください") 
    end
  end
    validate :begin_day__after__finish_day, on: :create
  def begin_day__after__finish_day
    errors.add(:begin_day, "終了日は開始日以降のものを選択してください") unless begin_day.to_s < finish_day.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end
  
  def new
    @posts = Post.new
  end
 
      def create
        @posts = Post.new(params.require(:post).permit(:title,:begin_day,:finish_day,:all_day,:schejule_memo))
    if @posts.valid?(:step1) && @posts.save
      flash[:notice] = "ユーザーを新規登録しました"
      redirect_to :posts
    else
      render "new"
    end
      end
 
      def show
        @post = Post.find(params[:id])
      end
 
      def edit
        @posts = Post.find(params[:id])
      end
 
      def update
        @posts = Post.find(params[:id])
    if @posts.update(params.require(:post).permit(:title,:begin_day,:finish_day,:all_day,:schejule_memo))
      flash[:notice] = "ユーザーIDが「#{@posts.id}」の情報を更新しました"
      redirect_to:posts
    else
      render "edit"
    end
      end
 
      def destroy
        @post = Post.find(params[:id])
    @post.destroy
    flash[:notice]="ユーザーを削除しました"
    redirect_to :posts
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <h2 class="title">Ruby on Rails スケジュール管理アプリ</h2>
    </header>
    <%= yield %>
    <footer>
  <h2 class = "title"><%= Date.current.strftime("現在の日時："+'%Y年 %m月 %d日') %><% if controller.controller_name == 'posts' && controller.action_name == 'index' %>　　スケジュール合計 : <%= Post.all.count(:id)%></h2>
<% end %>
    </footer>
  </body>
</html>

app/views/posts/edit.html.erb
 <h3>ユーザー編集</h3>
 
  <%= render "shared/error", obj: @posts %>
 
    <%= form_for @posts do |f| %>
      <table>
        <tr>
          <th><%= f.label :title ,"タイトル" %></th>
          <td><%= f.text_field :title %></td>
        </tr>
        <tr>
          <th><%= f.label :begin_day ,"開始日" %></th>
          <td><%= f.date_field :begin_day,  class: 'form-control' %></td>
        </tr>
        <tr>
          <th><%= f.label :finish_day ,"終了日" %></th>
          <td><%= f.date_field:finish_day ,class: 'form-control' %></td>
        </tr>
        <tr>
          <th><%= f.label :all_day ,"終日" %></th>
          <td><%= f.check_box :all_day %><br><%="終日の場合はチェックを入れます" %></td>
        </tr>
        <tr>
          <th><%= f.label :schejule_memo ,"スケジュールメモ" %></th>
          <td><%= f.text_area :schejule_memo %></td>
        </tr>
      </table>
      <div>
        <ul>
          <li><%= f.submit "編集を完了する" %></li>
          <li><%= link_to "ユーザー情報一覧に戻る", :posts %></li>
        </ul>
      </div>
    <% end %>

app/views/posts/index.html.erb
<h3>スケジュール一覧</h3>

<% if flash.notice %>
<p class="notice"><%= flash.notice %></p>
<% end %>

  <table>
   <thead>
    <tr>
     <th>ID</th>
     <th>タイトル</th>
     <th>開始日</th>
     <th>終了日</th>
     <th>終日</th>
     <th>スケジュール更新日時</th>
     <th>確認</th>
     <th>編集</th>
     <th>削除</th>
    </tr>
   </thead>
    
   <tbody>
    <% @posts.each do |post| %>
     <tr>
      <td><%= post.id %></td>
      <td><%= post.title %></td>
      <td><%= post.begin_day&.strftime("%Y年 %m月 %d日") %></td>
      <td><%= post.finish_day&.strftime("%Y年 %m月 %d日") %></td>
      <td><% if post.all_day == '1' then %>○<% else%><% end %>︎</td>
      <td><%= post.schejule_memo %></td>
      <td>
       <%= link_to "確認", post %>
      </td>
      <td>
       <%= link_to "編集", [:edit, post]%>
      </td>
      <td>
       <%= link_to "削除", post, method: :delete, data: { confirm: "本当に削除しますか？" } %>
      </td>

     </tr>
    <% end %>
   </tbody>
  </table>
 
  <p><%= link_to "スケジュール新規登録", :new_post %></p>
  

app/views/posts/new.html.erb
 <h3>スケジュール新規作成</h3>
 
 <%= render "shared/error", obj: @posts %>
 
 <%= form_for @posts do |f| %>
 <table>
     <tr>
         <th><%= f.label :title ,"タイトル" %></th>
         <td><%= f.text_field :title %></td>
     </tr>
     
     <tr>
          <th><%= f.label :begin_day ,"開始日" %></th>
          <td><%= f.date_field :begin_day,  class: 'form-control' %></td>
     </tr>
     
     <tr>
          <th><%= f.label :finish_day ,"終了日" %></th>
          <td><%= f.date_field:finish_day ,class: 'form-control' %></td>
     </tr>
     
     <tr>
          <th><%= f.label :all_day ,"終日" %></th>
    <td><%= f.check_box :all_day %><br><%="終日の場合はチェックを入れます" %></td>
     </tr>
     
     <tr>
          <th><%= f.label :schejule_memo ,"スケジュールメモ" %></th>
          <td><%= f.text_area :schejule_memo %></td>
     </tr>
 </table>
     
     <div>
         <ul>
             <li><%= f.submit "スケジュールを新規作成する"%></li>
             <li><%= link_to "スケジュール一覧に戻る", :posts %></li>
         </ul>
     </div>
 <% end %>
 

app/views/posts/show.html.erb
 <h3>スケジュール詳細</h3>
 
 <table>
     <tr>
        <th>タイトル</th>
        <th><%= @post.title %></th>
     </tr>
     
     <tr>
        <th>開始日</th>
        <th><%= @post.begin_day.strftime("%Y年 %m月 %d日") %></th>
     </tr>
     
     <tr>
        <th>投稿日時</th>
        <th><%= @post.finish_day.strftime("%Y年 %m月 %d日") %></th>
     </tr>
     
     <tr>
        <th>終日</th>
        <th><% if @post.all_day == '1' then %>○<% else%><% end %></th>
     </tr>
     
     <tr>
        <th>スケジュールメモ</th>
        <th><%= @post.schejule_memo %></th>
     </tr>
     </table>
     
     <div>
      <ul>
        <li><%= link_to "スケジュール一覧に戻る", posts_path(@post) %></li>
        <li><%= link_to "スケジュールを編集する", [:edit, @post] %></li>
        <li><%= link_to "スケジュールを削除", post_path(@post), method: :delete, data: { confirm: "本当に削除しますか？"} %></li>
      </ul>
    </div>
    
  

app/views/shared/_error.html.erb
    <% if obj.errors.any? %>
      <% obj.errors.full_messages.each do |message| %>
        <ul>
          <li><%= message %></li>
        </ul>
      <% end %>
    <% end %>

app/views/shared/_partial.html.erb
 <span id="view_time"></span>

<script type="text/javascript">
document.getElementById("view_time").innerHTML = getNow();

function getNow() {
	var now = new Date();
	var year = now.getFullYear();
	var mon = now.getMonth()+1; //１を足すこと
	var day = now.getDate();

	//出力用
	var s = "現在の日時:"+year + "年" + mon + "月" + day + "日"; 
	return s;
}
</script>

  <p class="date_now"><%= Date.current.strftime("現在の日時："+'%Y年 %m月 %d日') %></p>
  <p class="id_count"><%= Post.all.count(:id)%></p>